### ISSUE TITLE
Contrast issues

### ISSUE THREAD

**Issue by danielweck** [edrlab/r2-desktop-ui#11]
~~http://wave.webaim.org/report#/https://rawgit.com/edrlab/r2-desktop-ui/master/index.html~~
http://wave.webaim.org/report#/https://edrlab.github.io/r2-desktop-ui/index.html

**Comment by danielweck** [comment]
https://achecker.ca/checkacc.php?id=ce4ea9c64ffe38eac3a2302d71a97ce3dae89c6a&uri=https://edrlab.github.io/r2-desktop-ui/index.html

Or alternatively copy/paste the URL `https://edrlab.github.io/r2-desktop-ui/index.html` into this form:
https://achecker.ca/checker/index.php

**Comment by danielweck** [comment]
FAE report:
https://fae.disability.illinois.edu/pages/166819e6a29e52de/rc/all/page/1/

**Comment by danielweck** [comment]
Tenon.io:
https://tenon.io/testNow.php?url=https://edrlab.github.io/r2-desktop-ui/index.html

**Comment by danielweck** [comment]
...and of course Axe (used by DAISY Ace, Google's own Lighthouse, etc.)

Chrome:
https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd
Lighthouse:
https://github.com/GoogleChrome/lighthouse

Firefox:
https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/

**Comment by llemeurfr** [comment]
Re. tenon.io I'm surprised to see an issue with "empty buttons" where the buttons have a title attribute and aria attributes also...

**Comment by vaninoor** [comment]
I just changed the CSS. It is now possible to darken all greys on the website by changing the class "lightgrey" and the placeholders which are right under it. I darkened it too, it should be better!
