### ISSUE TITLE
In a modal, a screen reader user should not interact with the inert content

### ISSUE THREAD

**Issue by alexbernier** [edrlab/r2-desktop-ui#5]
In index.html (div id="dialog"), it is possible for a screen reader to view and interact with the content located outside the modal.

To avoid this : wrap all the <div id="dialog"...> siblings into a "div" with aria-hidden="true"

**Comment by danielweck** [comment]
Note that modal dialogs are correctly implemented in `readium-desktop`, this was addressed some time ago using a React off-the-shelf library ("focus lock"), see issue:
https://github.com/readium/readium-desktop/issues/61
